"use strict";var bootArgs=JSON.parse(document.getElementById("boot_args").textContent);window.idms=window.idms||{};window.idms.app_config=window.idms.app_config||{};window.idms.app_config.bootData=window.idms.app_config.bootData||{};var bootData=window.idms.app_config.bootData;if(typeof bootArgs.direct==='object'){Object.keys(bootArgs.direct).forEach(function(key){bootData[key]=bootArgs.direct[key];});}
function getBootArgsVal(pathElements){if(typeof bootArgs.additional!=='object'){return undefined;}
var bootArgsVal=bootArgs.additional;for(var i in pathElements){var pathElement=pathElements[i];if(typeof bootArgsVal[pathElement]!=="undefined"){bootArgsVal=bootArgsVal[pathElement];}else{bootArgsVal=undefined;break;}}
return bootArgsVal;}
function setBootDataValue(pathElements,valueToSet){var bootDataVal=bootData;var pathElementsExceptLast=pathElements.slice(0,-1);var valid=true;for(var i in pathElementsExceptLast){var pathElement=pathElementsExceptLast[i];if(typeof bootDataVal[pathElement]==='undefined'){bootDataVal[pathElement]={};}
if(typeof bootDataVal[pathElement]==='object'){bootDataVal=bootDataVal[pathElement];}else{valid=false;break;}}
var lastPathElement=pathElements[pathElements.length-1];if(valid){bootDataVal[lastPathElement]=valueToSet;}}
function useIfExists(pathToModify,modificationFunc){if(typeof pathToModify!=='string'||!pathToModify){return;}
var pathElements=pathToModify.split(/\./);if(pathElements.length===0){return;}
var bootArgsVal=getBootArgsVal(pathElements);if(!bootArgsVal){return;}
if(typeof modificationFunc!=='function'){modificationFunc=function(val){return val;};}
var valueToSet=modificationFunc(bootArgsVal);setBootDataValue(pathElements,valueToSet);}
useIfExists("options.appContext",function(val){return val.slice(0,-1);});useIfExists("options.initialRoute");useIfExists("options.clientCountryCode",function(val){return val||'US';});useIfExists("appContext",function(val){return val.slice(0,-1);});useIfExists("clientCountryCode",function(val){return val||'US';});useIfExists("locale",function(val){return val||'en_US';});useIfExists("appContextHasSettings",function(val){return val.indexOf("/settings")!==-1;});useIfExists("returnUrl",function(val){return encodeURIComponent(val);});useIfExists("returnURL",function(val){return encodeURIComponent(val);});useIfExists("authInitOptions.logo.src",function(val){if(typeof val==='string'&&/^https:\/\//i.test(val)){return val;}
if(!window.location.origin){window.location.origin=window.location.protocol+"//"+window.location.hostname+(window.location.port?':'+window.location.port:'');}
return window.location.origin+val;});useIfExists("authInitOptions.features.enableFirstPartyOAuth",function(val){return val.toLowerCase()==='true';});useIfExists("authInitOptions.features.enableOIDCGrantCode",function(val){return val.toLowerCase()==='true';});useIfExists("destinationDomain",function(val){if(val.substr(-1)!=='/'){return val;}
return val.slice(0,-1);});useIfExists("account.primary");useIfExists("account.exceedVerificationAttempts");useIfExists("error",function(val){if(Array.isArray(val)){if(val[0]){return val[0];}}
return null;});useIfExists("useNew",function(val){if(!val){return val;}
return(typeof window!=='undefined'&&typeof window.InternetAccount2!=='undefined'&&typeof window.InternetAccount2.environment!=='undefined'&&typeof window.InternetAccount2.environment.currentApplication!=='undefined'&&(window.InternetAccount2.environment.currentApplication==='com.apple.preferences.AppleIDPrefPane.remoteservice'||window.InternetAccount2.environment.currentApplication==='com.apple.systempreferences.AppleIDSettings'));});useIfExists("useNewExt",function(val){if(!val){return val;}
return(typeof window!=='undefined'&&typeof window.InternetAccount2!=='undefined'&&typeof window.InternetAccount2.environment!=='undefined'&&typeof window.InternetAccount2.environment.currentApplication!=='undefined'&&window.InternetAccount2.environment.currentApplication==='com.apple.systempreferences.AppleIDSettings');});if(bootData.scntRequired===true){window.AppleID.service.JSLogger.setSCNT(bootData.scnt);}
bootData.fragmentLoad=function(){var fragmentArgs=JSON.parse(document.getElementById("create_fragment_args").textContent);var loadSource=function(){var el=document.createElement('script'),scPath=fragmentArgs.scPath;document.getElementById('createdata').appendChild(el);el.src=scPath.substring(scPath.lastIndexOf('src=&quot;')+10,scPath.lastIndexOf('&quot;'));};var loadAppConfig=function(){var appConfig={bootData:{config:fragmentArgs.config},i18n_legacy:[]};if(window.idms&&window.idms.app_config&&window.idms.app_config.loadAppConfig){window.idms.app_config.loadAppConfig({scriptId:'create_app_config',appConfig:appConfig});}};loadAppConfig();loadSource();};